# Generated by Django 5.0.6 on 2024-05-23 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=12)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unique_code', models.CharField(blank=True, max_length=40, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=223)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В пути'), (2, 'Доставлен'), (3, 'Отменен'), (4, 'В обработке')], default=4)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
