# Generated by Django 5.0.6 on 2024-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='cap',
            new_name='product',
        ),
    ]
